version: 2.0.0
skip_non_tags: true
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 $env:APPVEYOR_BUILD_VERSION ''
test_script:
- ps: .\tests.ps1
artifacts:
- path: build\release\*.nupkg
  name: Nuget Releases
deploy:
- provider: NuGet
  api_key:
    secure: TGpT22WUw2TfAVU5l03mIVKIlwpD7UauiWCE2oPh/ENM65h1u58k04YUAgIfCWWj
  on:
    branch: master